#!/usr/bin/env python3

import atexit
import os
import platform
import shutil
import subprocess
import sys
import tempfile

NoneType = type(None)
function = type(lambda: 0)

programs_info = [
    # env. name     default
    ("CC", "cc"),
    ("PKG_CONFIG", "pkg-config"),
    ("WINDRES", "windres"),
    ("GIT", "git"),
    ("NINJA", "ninja"),
]

install_paths_info = [
    ("PREFIX", "/usr/local"),
]

other_env_vars = [
    ("CFLAGS", "User C compiler flags to append."),
    ("CPPFLAGS", "Also treated as C compiler flags."),
    ("LDFLAGS", "C compiler flags for link command."),
    ("CCACHE", "Set to 'no' to disable automatic ccache detection."),
    ("TARGET", "Prefix for default build tools (for cross compilation)."),
    ("CROSS_COMPILE", "Same as TARGET."),
]


class _G:
    help_mode = False
    log_file = None
    temp_path = None
    build_dir = "build"
    root_dir = "."
    install_paths = {}
    programs = {}
    exe_format = "elf"
    cflags = []
    ldflags = []
    config_h = ""
    config_mak = ""
    sources = []
    state_stack = []
    feature_opts = {}
    dep_enabled = {}


def _c_quote_string(s):
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    return '"%s"' % s


def die(msg):
    sys.stderr.write("Fatal error: %s\n" % msg)
    sys.stderr.write("Not updating build files.\n")
    if _G.log_file:
        _G.log_file.write("--- Stopping due to error: %s\n" % msg)
    sys.exit(1)


def begin():
    _G.install_paths["PROJNAME"] = "lachesis"
    for var, val in install_paths_info:
        _G.install_paths[var] = val

    for arg in sys.argv[1:]:
        if not arg.startswith("-"):
            die("Unknown argument: %s" % arg)
        name = arg.lstrip("-")
        opt = name.split("=", 1)
        name, val = opt[0], (opt[1] if len(opt) > 1 else "")

        def noval():
            if val:
                die("Option --%s does not take a value." % name)

        if name == "help":
            noval()
            _G.help_mode = True
        elif name.startswith("enable-"):
            noval()
            _G.feature_opts[name[7:]] = "yes"
        elif name.startswith("disable-"):
            noval()
            _G.feature_opts[name[8:]] = "no"
        elif name.startswith("with-"):
            if val not in ["yes", "no", "auto", "default"]:
                die("Option --%s requires 'yes', 'no', 'auto', or 'default'." % name)
            _G.feature_opts[name[5:]] = val
        elif name.upper() == "PREFIX":
            if not val:
                die("Option --prefix requires a value.")
            _G.install_paths["PREFIX"] = val
        else:
            die("Unknown option: %s" % arg)

    if _G.help_mode:
        print("Environment variables controlling build tools:")
        for name, default in programs_info:
            print("  %-20s %s" % (name, default))
        print("\nOther environment variables:")
        for name, help in other_env_vars:
            print("  %-20s %s" % (name, help))
        print("\nInstall paths:")
        print("  %-20s %s (also --prefix)" % ("PREFIX", _G.install_paths["PREFIX"]))
        print("\nSpecific build configuration:")
        return

    _G.temp_path = tempfile.mkdtemp(prefix="lachesis-configure-")
    atexit.register(lambda: shutil.rmtree(_G.temp_path, ignore_errors=True))

    if os.path.exists(_G.build_dir):
        shutil.rmtree(_G.build_dir)
    os.makedirs(_G.build_dir, exist_ok=True)
    _G.log_file = open(os.path.join(_G.build_dir, "config.log"), "w")
    _G.config_h += "// Generated by configure.\n#pragma once\n\n"


def typecheck(val, *types):
    if type(val) not in types:
        raise Exception("Value '%s' of type %s not any of %s" % (val, type(val), types))
    return val


def normalize_list_arg(val):
    if val is None:
        return []
    if type(val) == list:
        return val
    return [val]


def push_build_flags():
    _G.state_stack.append(
        (_G.cflags[:], _G.ldflags[:], _G.config_h, _G.config_mak, _G.programs.copy())
    )


def pop_build_flags_discard():
    _G.cflags[:], _G.ldflags[:], _G.config_h, _G.config_mak, _G.programs = (
        _G.state_stack.pop()
    )


def pop_build_flags_merge():
    _G.state_stack.pop()


def get_build_dir():
    return _G.build_dir


def get_root_dir():
    return _G.root_dir


def set_exe_format(fmt):
    assert fmt in ["elf", "pe", "macho"]
    _G.exe_format = fmt


def chain(*a):
    return a[-1]


def check(
    name=None,
    desc=None,
    deps=None,
    deps_any=None,
    deps_neg=None,
    sources=None,
    fn=None,
    required=None,
    default=None,
):
    deps = normalize_list_arg(deps)
    deps_any = normalize_list_arg(deps_any)
    deps_neg = normalize_list_arg(deps_neg)
    sources = normalize_list_arg(sources)

    typecheck(name, str, NoneType)
    typecheck(fn, NoneType, function)

    option_name = None
    define_name = None
    if name is not None:
        opt_flag = name.startswith("-")
        if opt_flag:
            name = name[1:]
        def_flag = name.endswith("*")
        if def_flag:
            name = name[:-1]
        if opt_flag:
            option_name = name.replace("_", "-")
        if def_flag:
            define_name = "HAVE_" + name.replace("-", "_").upper()

    if desc is None and name is not None:
        desc = name

    if _G.help_mode:
        if not option_name:
            return
        if required is not None:
            return
        if default is False:
            defaction = "disable"
        elif deps or deps_any or deps_neg or fn:
            defaction = "autodetect"
        else:
            defaction = "enable"
        act = "enable" if defaction == "disable" else "disable"
        print(
            "  %-28s %s %s [%s]"
            % ("--%s-%s" % (act, option_name), act, desc, defaction)
        )
        return

    _G.log_file.write("\n--- Test: %s\n" % (name if name else "(unnamed)"))
    if desc:
        sys.stdout.write("Checking for %s... " % desc)
    outcome = "yes"

    force_opt = required is not None
    use_dep = True if default is None else default

    if option_name:
        val = _G.feature_opts.pop(option_name, "default")
        if val == "yes":
            use_dep = True
            force_opt = True
        elif val == "no":
            if required is not None:
                die("Feature '%s' is required and cannot be disabled." % option_name)
            use_dep = False
            force_opt = False
        elif val == "auto":
            use_dep = True

    if not use_dep:
        outcome = "disabled"

    for d in deps_neg + deps_any + deps:
        dep_enabled(d)
    if use_dep:
        for d in deps_neg:
            if dep_enabled(d):
                use_dep = False
                outcome = "conflicts with %s" % d
                break
    if use_dep and deps_any:
        if not any(dep_enabled(d) for d in deps_any):
            use_dep = False
            outcome = "not any of %s found" % (", ".join(deps_any))
    if use_dep:
        for d in deps:
            if not dep_enabled(d):
                use_dep = False
                outcome = "%s not found" % d
                break

    if use_dep and fn:
        push_build_flags()
        if fn():
            pop_build_flags_merge()
        else:
            pop_build_flags_discard()
            use_dep = False
            outcome = "no"

    if name:
        _G.dep_enabled[name] = use_dep
    if define_name:
        add_config_h_define(define_name, 1 if use_dep else 0)
    if use_dep:
        _G.sources += sources
    if desc:
        sys.stdout.write("%s\n" % outcome)
    _G.log_file.write(
        "--- Outcome: %s (%s=%d)\n" % (outcome, name if name else "(unnamed)", use_dep)
    )

    if required is not None and not use_dep:
        print("Warning: %s" % required)
    if force_opt and not use_dep:
        die("This feature is required.")


def _run_process(args):
    try:
        p = subprocess.Popen(
            args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=-1
        )
    except OSError as err:
        _G.log_file.write(
            "--- Command failed to start: %s (%s)\n" % (" ".join(args), err)
        )
        return None
    p_out, p_err = p.communicate()
    p_out = p_out.decode("utf-8", "replace")
    p_err = p_err.decode("utf-8", "replace")
    status = p.wait()
    _G.log_file.write("--- Command: %s\n" % " ".join(args))
    if p_out:
        _G.log_file.write("--- stdout:\n%s" % p_out)
    if p_err:
        _G.log_file.write("--- stderr:\n%s" % p_err)
    _G.log_file.write("--- Exit status: %s\n" % status)
    return p_out if status == 0 else None


def check_cc(
    include=None,
    decl=None,
    expr=None,
    defined=None,
    flags=None,
    link=None,
    language="c",
):
    assert language in ["c", "m"]
    use_linking = link is not None

    contents = ""
    for inc in normalize_list_arg(include):
        contents += "#include <%s>\n" % inc
    for dec in normalize_list_arg(decl):
        contents += "%s\n" % dec
    for define in normalize_list_arg(defined):
        contents += "#ifndef %s\n#error failed\n#endif\n" % define
    if expr or use_linking:
        contents += "int main(int argc, char **argv) {\n"
        if expr:
            contents += expr + "\n"
        contents += "return 0; }\n"

    source = os.path.join(_G.temp_path, "test." + language)
    _G.log_file.write("--- Test file %s:\n%s" % (source, contents))
    with open(source, "w") as f:
        f.write(contents)

    flags = normalize_list_arg(flags)
    link = normalize_list_arg(link)
    outfile = os.path.join(_G.temp_path, "test")
    args = get_program("CC").split() + [source] + _G.cflags + flags
    if use_linking:
        args += _G.ldflags + link + ["-o%s" % outfile]
    else:
        args += ["-c", "-o%s.o" % outfile]
    if _run_process(args) is None:
        return False
    _G.cflags += flags
    _G.ldflags += link
    return True


# Some linkers accept unsupported options.
def check_ldflags(*flags, fatal_warnings=False):
    test_flags = list(flags)
    if fatal_warnings:
        test_flags += ["-Wl,--fatal-warnings"]
    if not check_cc(link=test_flags):
        return False
    if fatal_warnings:
        _G.ldflags = [f for f in _G.ldflags if f != "-Wl,--fatal-warnings"]
    return True


def check_pkg_config(*args):
    args = list(args)
    pkg = [get_program("PKG_CONFIG")]
    cflags = _run_process(pkg + ["--cflags"] + args)
    if cflags is None:
        return False
    ldflags = _run_process(pkg + ["--libs"] + args)
    if ldflags is None:
        return False
    _G.cflags += cflags.split()
    _G.ldflags += ldflags.split()
    return True


def check_program(env_name):
    for name, default in programs_info:
        if name != env_name:
            continue
        val = os.environ.get(env_name)
        if val is None:
            prefix = os.environ.get("TARGET") or os.environ.get("CROSS_COMPILE", "")
            if prefix and default == "cc":
                default = "gcc"
            val = prefix + default
        if env_name == "CC":
            ccache_disabled = os.environ.get("CCACHE", "").lower() in {
                "no",
                "0",
                "false",
            }
            parts = val.split()
            has_ccache = parts and os.path.basename(parts[0]) == "ccache"
            if (
                not ccache_disabled
                and not has_ccache
                and _run_process(["ccache", "-V"]) is not None
            ):
                val = "ccache " + val
        sys.stdout.write("(%s) " % val)
        parts = val.split()
        test_cmd = (
            parts
            if (env_name == "CC" and len(parts) > 1)
            else [parts[0] if parts else val]
        )
        if (
            _run_process(test_cmd) is None
            and not os.path.basename(test_cmd[0]) == "ccache"
        ):
            if shutil.which(test_cmd[0]) is None:
                return False
        _G.programs[env_name] = val
        add_config_mak_var(env_name, val)
        return True
    assert False, "Unknown program name '%s'" % env_name


def get_program(env_name):
    val = _G.programs.get(env_name)
    assert val is not None, "get_program(%s) without successful check." % env_name
    return val


def dep_enabled(*deps):
    for d in deps:
        val = _G.dep_enabled.get(d)
        assert val is not None, "Internal error: unknown dependency %s" % d
        if not val:
            return False
    return True


def add_cflags(*fl):
    _G.cflags += list(fl)


def add_ldflags(*fl):
    _G.ldflags += list(fl)


def add_config_h_define(name, val):
    if isinstance(val, str):
        val = _c_quote_string(val)
    if val is None:
        val = ""
    _G.config_h += "#define %s %s\n" % (name, val)


def add_config_mak_var(name, val):
    _G.config_mak += "%s = %s\n" % (name, val)


def add_sources(*sources):
    _G.sources += list(sources)


def dedup_ldflags(flags):
    last_lib = {}
    for idx, f in enumerate(flags):
        if f.startswith("-l"):
            last_lib[f] = idx

    seen = set()
    out = []
    i = 0
    n = len(flags)
    while i < n:
        f = flags[i]
        if f.startswith("-l"):
            if last_lib[f] == i:
                out.append(f)
            i += 1
            continue
        if f in ("-framework", "-rpath") and i + 1 < n:
            unit, key, i = [f, flags[i + 1]], (f, flags[i + 1]), i + 2
        elif f == "-Wl,-rpath" and i + 1 < n and flags[i + 1].startswith("-Wl,"):
            unit, key, i = [f, flags[i + 1]], ("rpath", flags[i + 1][4:]), i + 2
        elif f.startswith("-Wl,-rpath,"):
            unit, key, i = [f], ("rpath", f[len("-Wl,-rpath,") :]), i + 1
        elif f.startswith("-L"):
            unit, key, i = [f], f, i + 1
        else:
            # Leave anything we don't understand untouched.
            out.append(f)
            i += 1
            continue
        if key not in seen:
            seen.add(key)
            out.extend(unit)
    return out


def _generate_ninja_file(sources, cflags_str, ldflags_str):
    cc = _G.programs.get("CC", "cc")
    build_dir = os.path.abspath(_G.build_dir)
    root_dir = os.path.abspath(_G.root_dir)
    exesuf = ".exe" if _G.exe_format == "pe" else ""

    # Pre-create object directories.
    for src in sources:
        rel = src.replace("$(ROOT)/", "").replace("$(BUILD)/", "")
        if rel.endswith(".c") or rel.endswith(".m"):
            os.makedirs(
                os.path.dirname(os.path.join(build_dir, rel)) or build_dir,
                exist_ok=True,
            )

    n = "# Generated by configure.\n\n"
    n += "builddir = %s\n" % build_dir
    n += "root = %s\n" % root_dir
    n += "cc = %s\n" % cc
    n += "cflags = %s\n" % cflags_str
    n += "ldflags = %s\n" % ldflags_str
    n += "exesuf = %s\n\n" % exesuf

    n += "rule cc\n"
    n += "  command = $cc $cflags -I$root -I$builddir -MMD -MF $out.d $in -c -o $out\n"
    n += "  description = CC $out\n"
    n += "  depfile = $out.d\n"
    n += "  deps = gcc\n\n"

    n += "rule link\n"
    n += "  command = $cc @$out.rsp $ldflags -o $out\n"
    n += "  description = LINK $out\n"
    n += "  rspfile = $out.rsp\n"
    n += "  rspfile_content = $in\n\n"

    objects = []
    n += "# Object files\n"
    for src in sources:
        src_path = src.replace("$(BUILD)", "$builddir").replace("$(ROOT)", "$root")
        if src.endswith(".c"):
            obj = src[:-2] + ".o"
        elif src.endswith(".m"):
            obj = src[:-2] + ".o"
        else:
            continue
        obj_path = obj.replace("$(ROOT)/", "$builddir/").replace(
            "$(BUILD)/", "$builddir/"
        )
        objects.append(obj_path)
        n += "build %s: cc %s\n" % (obj_path, src_path)
    n += "\n"

    target = "$builddir/lachesis$exesuf"
    n += "build %s: link %s\n\n" % (target, " ".join(objects))
    n += "default %s\n\n" % target

    prefix = _G.install_paths.get("PREFIX", "/usr/local")
    n += "rule install_rule\n"
    # Just Windows shenanigans..
    n += (
        '  command = sh -c "mkdir -p %s/bin && install -v -m 0755 %s %s/bin/lachesis%s"\n'
        % (
            prefix,
            target,
            prefix,
            exesuf,
        )
    )
    n += "  description = INSTALL\n\n"
    n += "build install: install_rule | %s\n\n" % target
    return n


def finish():
    if _G.help_mode:
        return

    fatal = False
    for key, val in _G.feature_opts.items():
        print("Unknown feature set on command line: %s" % key)
        if val == "yes":
            fatal = True
    if fatal:
        die("Unknown feature was force-enabled.")

    _G.ldflags = dedup_ldflags(_G.ldflags)

    add_config_h_define("CONFIGURATION", " ".join(sys.argv))
    enabled = sorted(k for k, v in _G.dep_enabled.items() if v)
    add_config_h_define("FULLCONFIG", " ".join(enabled))
    with open(os.path.join(_G.build_dir, "config.h"), "w") as f:
        f.write(_G.config_h)

    add_config_mak_var("BUILD", _G.build_dir)
    add_config_mak_var("ROOT", _G.root_dir)
    add_config_mak_var("EXESUF", ".exe" if _G.exe_format == "pe" else "")
    _G.config_mak += "\n"
    _G.config_mak += "CFLAGS = %s %s %s\n" % (
        " ".join(_G.cflags),
        os.environ.get("CPPFLAGS", ""),
        os.environ.get("CFLAGS", ""),
    )
    _G.config_mak += "LDFLAGS = %s %s\n" % (
        " ".join(_G.ldflags),
        os.environ.get("LDFLAGS", ""),
    )

    sources = []
    for s in _G.sources:
        assert not s.startswith("$")
        sources.append("$(ROOT)/%s" % s)
    sources = sorted(set(sources))
    _G.config_mak += (
        "SOURCES = \\\n" + "".join("   %s \\\n" % s for s in sources) + "\n"
    )
    with open(os.path.join(_G.build_dir, "config.mak"), "w") as f:
        f.write("# Generated by configure.\n\n" + _G.config_mak)

    cflags_str = (
        " ".join(_G.cflags)
        + " "
        + os.environ.get("CPPFLAGS", "")
        + " "
        + os.environ.get("CFLAGS", "")
    ).strip()
    ldflags_str = (" ".join(_G.ldflags) + " " + os.environ.get("LDFLAGS", "")).strip()
    with open(os.path.join(_G.build_dir, "build.ninja"), "w") as f:
        f.write(_generate_ninja_file(sources, cflags_str, ldflags_str))

    print("Done. You can run 'ninja -C %s' now." % _G.build_dir)
