name: lachesis macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig
      DYLD_FALLBACK_LIBRARY_PATH: /usr/local/lib:/opt/homebrew/lib

    steps:
      - name: actions/checkout@v7
        uses: actions/checkout@v7

      - name: Setup ccache
        uses: actions/cache@v6
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: dependencies
        run: |
          set -x

          brew update
          brew install \
            ccache \
            cmake \
            meson \
            ninja \
            nasm \
            yasm \
            pkg-config \
            sdl3 \
            sdl3_ttf \
            libarchive \
            shaderc \
            glslang \
            molten-vk \
            vulkan-headers \
            vulkan-loader

          git clone --depth 1 --recursive https://github.com/haasn/libplacebo.git
          cd libplacebo
          meson setup --prefix=/usr/local -Dlibdir=lib build
          ninja -v -C build
          sudo ninja -C build install
          cd ..

          git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          ./configure --prefix=/usr/local \
                      --enable-libplacebo \
                      --enable-vulkan \
                      --cc="ccache cc"
          make -j$(sysctl -n hw.ncpu)
          sudo make install
          cd ..

      - name: Configure ccache
        run: |
          ccache --version
          ccache --set-config=cache_dir=$HOME/.ccache
          ccache --set-config=max_size=999M
          ccache --set-config=compression=true
          ccache --zero-stats
          mkdir -p $HOME/.ccache

      - name: configure, build, install, test
        run: |
          set -x

          export PKG_CONFIG_PATH="$(brew --prefix libarchive)/lib/pkgconfig:$PKG_CONFIG_PATH"
          ./configure

          ninja -v -C build
          sudo ninja -C build install

          lachesis -h
