name: lachesis OpenBSD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout@v7
        uses: actions/checkout@v7

      - name: Install dependencies, build, run
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            set -x
            pkg_add ccache cmake ffmpeg git gmake libarchive libevdev-openbsd libinput-openbsd libplacebo libxkbcommon mpv ninja sdl3 wayland wayland-protocols

            git clone --depth 1 https://github.com/libsdl-org/SDL_ttf.git
            cd SDL_ttf
            mkdir build
            cd build
            cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON
            make install
            ln -sf "$(ls /usr/local/lib/libSDL3_ttf.so.* | sort -V | tail -1)" /usr/local/lib/libSDL3_ttf.so
            
          run: |
            set -x

            git config --global --add safe.directory "$PWD"
            export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig
            ./configure
            ninja -v -C build
            ./build/lachesis -h
